marketplace_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: marketplace-analytics-485915
      dataset: analytics
      threads: 4
      keyfile: /opt/airflow/.dbt/service-account-key.json  # Changed to container path
      location: EU

    prod:
      type: bigquery
      method: service-account
      keyfile: /opt/airflow/.dbt/service-account-key.json  # Updated to match volume mount
      project: marketplace-analytics-485915
      dataset: analytics
      threads: 4
      location: EU
      timeout_seconds: 300
    
